baseurl = "/"
title = "Go|oG"
theme = "ghostwriter"
languageCode = "en-us"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Go|oG"
    description = "A place for learning Go"
    github = "https://github.com/hanmd82"
    twitter = "https://twitter.com/hanmd82"
    linkedin = "https://www.linkedin.com/in/mingdinghan/"
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 1

[[menu.main]]
    name = "Study"
    url = "/study/"
    weight = 2

[[menu.main]]
    name = "Practice"
    url = "/practice/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4

[[menu.main]]
    name = "Resources"
    url = "/resource/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 6
